/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ObraController;
import Controller.TermoController;
import javax.swing.JOptionPane;
import Controller.TermoController;
import javax.swing.table.DefaultTableModel;
import model.Obra;
import model.Termo;
import java.util.ArrayList;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import model.Tabelas.TermoTableModel;

/**
 *
 * @author duda2
 */
public class Cad_Termo extends javax.swing.JFrame {

    /**
     * Creates new form Cad_Termo
     */
    public Cad_Termo() {
        initComponents();
        PreencheCombo();
        Tabela(3);
    }

    TermoController termoController = new TermoController();
    ArrayList<Termo> termo = termoController.PegarTodosTermos();
    ObraController obraController = new ObraController();
    ArrayList<Obra> obra = obraController.PegarTodasObras();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnCadTermo = new java.awt.Panel();
        lbNome = new javax.swing.JLabel();
        lbDescricao = new javax.swing.JLabel();
        lbObra = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        cbObra = new javax.swing.JComboBox<>();
        spTermo = new javax.swing.JScrollPane();
        tbTermo = new javax.swing.JTable();
        btSalvar = new javax.swing.JButton();
        btRemover = new javax.swing.JButton();
        lbTituloTela = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("jfTermo"); // NOI18N

        lbNome.setText("Nome:");
        lbNome.setToolTipText("");
        lbNome.setName("lbnome"); // NOI18N

        lbDescricao.setText("Descrição:");
        lbDescricao.setToolTipText("");
        lbDescricao.setName("lbDescricao");

        lbObra.setText("Obra:");
        lbObra.setToolTipText("");
        lbObra.setName("lbobra"); // NOI18N

        txtNome.setName("txtNome");

        txtDescricao.setName("txtnome"); // NOI18N

        cbObra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tbTermo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Descrição", "Obra"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        spTermo.setViewportView(tbTermo);

        btSalvar.setText("Incluir");
        btSalvar.setName("btSalvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btRemover.setText("Remover");
        btRemover.setName("btRemover"); // NOI18N
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnCadTermoLayout = new javax.swing.GroupLayout(pnCadTermo);
        pnCadTermo.setLayout(pnCadTermoLayout);
        pnCadTermoLayout.setHorizontalGroup(
            pnCadTermoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCadTermoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnCadTermoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCadTermoLayout.createSequentialGroup()
                        .addGroup(pnCadTermoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDescricao, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbObra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnCadTermoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDescricao)
                            .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                            .addComponent(cbObra, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCadTermoLayout.createSequentialGroup()
                        .addComponent(spTermo, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(pnCadTermoLayout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(btSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btRemover)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnCadTermoLayout.setVerticalGroup(
            pnCadTermoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCadTermoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnCadTermoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnCadTermoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDescricao)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnCadTermoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbObra)
                    .addComponent(cbObra, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spTermo, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnCadTermoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar)
                    .addComponent(btRemover))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        lbTituloTela.setFont(new java.awt.Font("Microsoft JhengHei", 1, 48)); // NOI18N
        lbTituloTela.setText("Cadastro de Termo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(pnCadTermo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(lbTituloTela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTituloTela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(pnCadTermo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(464, 464, 464))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        // TODO add your handling code here:
        try {
            VerificaCampo();
            Acoes(1);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, "Ocorreu uma exceção:\n" + e.toString(), "Exceção", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btSalvarActionPerformed

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
        // TODO add your handling code here:
        try {
            Acoes(2);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, "Ocorreu uma exceção:\n" + e.toString(), "Exceção", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btRemoverActionPerformed

    private void Tabela(int Crud) {
        DefaultTableModel Termo = (DefaultTableModel) tbTermo.getModel();
        Termo.setColumnIdentifiers(new Object[]{"Nome", "Descricao", "Obra"});
        switch (Crud) {
            case 1:
                Object[] newrow = {txtNome.getText(), txtDescricao.getText(), (String) cbObra.getSelectedItem()};
                Termo.addRow(newrow);
                break;
            case 2:
                int result = JOptionPane.showConfirmDialog(null, "Deseja Excluir a linha ? ", "Excluir", JOptionPane.YES_NO_CANCEL_OPTION);
                if (result == JOptionPane.YES_OPTION) {
                    int linhaSelecionada = tbTermo.getSelectedRow();
                    if (linhaSelecionada != -1) { // se não estiver em  nenhuma linha então 
                        ((DefaultTableModel) tbTermo.getModel()).removeRow(linhaSelecionada);
                    }
                }
                break;
            case 3:
                for (Termo dado : termo) {
                    Termo.addRow(new Object[]{dado.getDescricao(), dado.getNome(), dado.getObras()});
                }
                tbTermo = new JTable(new TermoTableModel(termo));
                spTermo = new JScrollPane(tbTermo);
                getContentPane().add(spTermo);

                break;
            default:
                throw new IllegalArgumentException("Tentou né");
        }
    }

    ;
     
     
    public void Acoes(int crud) {
        switch (crud) {
            case 1:
                String selectedObraTitulo = (String) cbObra.getSelectedItem();
                Obra selectedObra = obraController.VerObraPorTitulo(selectedObraTitulo);
                termoController.AdicionarTermo(txtNome.getText(), txtDescricao.getText(), selectedObra);
                Tabela(1);
                break;
            case (2):
                int linhaselecionada = tbTermo.getSelectedRow();
                if (linhaselecionada != -1) {
                    String nomeTermo = (String) tbTermo.getValueAt(linhaselecionada, 0);
                    termoController.RemoverTermo(nomeTermo);
                    ((DefaultTableModel) tbTermo.getModel()).removeRow(linhaselecionada);
                }
                break;
            default:
                throw new AssertionError();
        }

    }

    public void PreencheCombo() {
        cbObra.removeAllItems();

        for (Obra obras : obra) {
            cbObra.addItem(obras.getTitulo());
        }

    }; 
    
  
    
    private String VerificaCampo() {
        String VerificaCampo = " ";

        if (txtNome.getText().equals("") || txtDescricao.getText().equals("")
                || cbObra.getSelectedItem().equals("")) {

            VerificaCampo = "Campos que precisam ser preenchidos:";

            if (txtNome.getText().equals("")) {
                VerificaCampo += "\nCampo nome está vazio.";
            }
            if (txtDescricao.getText().equals("")) {
                VerificaCampo += "\nCampo descrição está vazio.";
            }
            if (cbObra.getSelectedItem().equals("")) {
                VerificaCampo += "\nCampo obra está vazio.";
            }

            JOptionPane.showMessageDialog(this, VerificaCampo, "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        return VerificaCampo;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cad_Termo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cad_Termo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cad_Termo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cad_Termo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Cad_Termo cadtermo = new Cad_Termo();

                if (cadtermo.obra != null && !cadtermo.obra.isEmpty()) {
                    new Cad_Termo().setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Não há pobras cadastradas no sistema ", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
                new Cad_Termo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRemover;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox<String> cbObra;
    private javax.swing.JLabel lbDescricao;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbObra;
    private java.awt.Label lbTituloTela;
    private java.awt.Panel pnCadTermo;
    private javax.swing.JScrollPane spTermo;
    private javax.swing.JTable tbTermo;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
