/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JOptionPane;
import Controller.ObraController;
import java.io.BufferedReader;
import javax.swing.table.DefaultTableModel;
import model.Obra;
import java.io.FileInputStream;
import java.io.InputStreamReader;
import java.util.ArrayList;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import model.Tabelas.ObraTableModel;

/**
 *
 * @author duda2
 */
public class Cad_Obra extends javax.swing.JFrame {

    /**
     * Creates new form Cad_Obra
     */
    public Cad_Obra() {
        initComponents();
        Tabela(3);
    }

    ObraController obraController = new ObraController();
    ArrayList<Obra> obra = obraController.PegarTodasObras();
    Obra obras = new Obra();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTituloTela = new java.awt.Label();
        pnCadObra = new java.awt.Panel();
        lbTitulo = new javax.swing.JLabel();
        lbAnoLancamento = new javax.swing.JLabel();
        lbCategoria = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtAnoLanca = new javax.swing.JTextField();
        btIncluir = new javax.swing.JButton();
        txtCategoria = new javax.swing.JTextField();
        spObra = new javax.swing.JScrollPane();
        tbObra = new javax.swing.JTable();
        btRemover = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("jfObra"); // NOI18N

        lbTituloTela.setFont(new java.awt.Font("Microsoft Tai Le", 1, 48)); // NOI18N
        lbTituloTela.setText("Cadastro de Obra");

        lbTitulo.setText("Título:");
        lbTitulo.setToolTipText("");
        lbTitulo.setName("lb_titulo"); // NOI18N

        lbAnoLancamento.setText("Ano de lançamento:");
        lbAnoLancamento.setName("lbanolancamento"); // NOI18N

        lbCategoria.setText("Categoria:");
        lbCategoria.setName("lbCategoria"); // NOI18N

        txtTitulo.setName("txttitulo"); // NOI18N

        txtAnoLanca.setName("txtano"); // NOI18N

        btIncluir.setText("Incluir");
        btIncluir.setName("btsalvar"); // NOI18N
        btIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncluirActionPerformed(evt);
            }
        });

        tbObra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Título", "Ano de lançamento", "Categoria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbObra.setName(""); // NOI18N
        spObra.setViewportView(tbObra);

        btRemover.setText("Remover");
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnCadObraLayout = new javax.swing.GroupLayout(pnCadObra);
        pnCadObra.setLayout(pnCadObraLayout);
        pnCadObraLayout.setHorizontalGroup(
            pnCadObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCadObraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnCadObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCategoria, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbAnoLancamento, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnCadObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAnoLanca, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(138, Short.MAX_VALUE))
            .addGroup(pnCadObraLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(lbTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTitulo)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCadObraLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(spObra, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnCadObraLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(btIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btRemover)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnCadObraLayout.setVerticalGroup(
            pnCadObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCadObraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnCadObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTitulo)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnCadObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAnoLancamento)
                    .addComponent(txtAnoLanca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnCadObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCategoria)
                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(spObra, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnCadObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btIncluir)
                    .addComponent(btRemover))
                .addContainerGap(365, Short.MAX_VALUE))
        );

        pnCadObraLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtAnoLanca, txtTitulo});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnCadObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lbTituloTela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lbTituloTela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(pnCadObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncluirActionPerformed
       try{
        VerificaCampo();
        Acoes(1);
        }
        catch(IllegalArgumentException e){
           JOptionPane.showMessageDialog(null, "Ocorreu uma exceção:\n" + e.toString(), "Exceção", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btIncluirActionPerformed

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
         try{          
         Acoes(2);
        }
        catch(IllegalArgumentException e){
           JOptionPane.showMessageDialog(null, "Ocorreu uma exceção:\n" + e.toString(), "Exceção", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btRemoverActionPerformed

    public void Tabela(int Crud) {
         DefaultTableModel Obras = (DefaultTableModel) tbObra.getModel();
         Obras.setColumnIdentifiers(new Object[]{"Título", "Ano de lançamento", "Categoria"});
        switch (Crud) {
            case 1: // salva  
                String[] newrow = {txtTitulo.getText(), txtAnoLanca.getText(), txtCategoria.getText()};
                Obras.addRow(newrow);
                break;
            case 2: // apaga 
                int result = JOptionPane.showConfirmDialog(null, "Deseja Excluir a linha ? ", "Excluir", JOptionPane.YES_NO_CANCEL_OPTION);
                if (result == JOptionPane.YES_OPTION) {
                    int linhaSelecionada = tbObra.getSelectedRow();
                    if (linhaSelecionada != -1) { // se não estiver em  nenhuma linha então 
                         
                        
                        ((DefaultTableModel) tbObra.getModel()).removeRow(linhaSelecionada);
                    }
                }
                break;
            case 3:  // preenche tabela                  
                for (Obra dado : obra) {
                    Obras.addRow(new Object[]{dado.getTitulo(), dado.getAnoLancamento(), dado.getCategoria()});
                }         
                break;
            default:
                throw new IllegalArgumentException("Tentou né");
        }
    };
    
   
    
    public void Acoes(int acoes) {

        switch (acoes) {
            case 1: // adicionando 
                obraController.AdicionarObra(txtTitulo.getText(),
                        txtAnoLanca.getText(),
                        txtCategoria.getText());
                Tabela(1);
                break;
            case 2: // removendo 
                  int linhaselecionada = tbObra.getSelectedRow();
                if (linhaselecionada != -1) {
                    String nomeObra = (String) tbObra.getValueAt(linhaselecionada, 0);
                    obraController.RemoverObra(nomeObra);
                    ((DefaultTableModel) tbObra.getModel()).removeRow(linhaselecionada);
                }
                break;
            default:
                throw new IllegalArgumentException("Error");
        }

    }

    public String VerificaCampo() {
        String VerificaCampo = " ";

        if (txtTitulo.getText().equals("") || txtAnoLanca.getText().equals("")
                || txtCategoria.getText().equals(" ")) {

            VerificaCampo = "Campos que precisam ser preenchidos:";

            if (txtTitulo.getText().equals("")) {
                VerificaCampo += "\nCampo título detalhada está vazio.";
            }
            if (txtAnoLanca.getText().equals("")) {
                VerificaCampo += "\nCampo ano de lançamento está vazio.";
            }
            if (txtCategoria.getText().equals(" ")) {
                VerificaCampo += "\nCampo categoria está vazio.";
            }

            JOptionPane.showMessageDialog(this, VerificaCampo, "ERRO", JOptionPane.ERROR_MESSAGE);

        }
        return VerificaCampo;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cad_Obra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cad_Obra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cad_Obra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cad_Obra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cad_Obra().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btIncluir;
    private javax.swing.JButton btRemover;
    private javax.swing.JLabel lbAnoLancamento;
    private javax.swing.JLabel lbCategoria;
    private javax.swing.JLabel lbTitulo;
    private java.awt.Label lbTituloTela;
    private java.awt.Panel pnCadObra;
    private javax.swing.JScrollPane spObra;
    private javax.swing.JTable tbObra;
    private javax.swing.JTextField txtAnoLanca;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
