/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author duda2
 */
public class Menu_Inicial extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro_Termos
     */
    public Menu_Inicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        btObra = new javax.swing.JButton();
        btTermo = new javax.swing.JButton();
        btPersonagem = new javax.swing.JButton();
        btLocal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setName("lb_titulo"); // NOI18N
        label1.setText("O que deseja cadastrar? ");

        btObra.setText("Obra");
        btObra.setName("btobra"); // NOI18N
        btObra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btObraMouseClicked(evt);
            }
        });

        btTermo.setText("Termo");
        btTermo.setToolTipText("");
        btTermo.setName("btTermo"); // NOI18N
        btTermo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btTermoMouseClicked(evt);
            }
        });
        btTermo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTermoActionPerformed(evt);
            }
        });

        btPersonagem.setText("Personagem");
        btPersonagem.setName("btPersonagem"); // NOI18N
        btPersonagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btPersonagemMouseClicked(evt);
            }
        });

        btLocal.setText("Local");
        btLocal.setToolTipText("");
        btLocal.setName("btLocal"); // NOI18N
        btLocal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btlocalMouseClicked(evt);
            }
        });
        btLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLocalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btTermo)
                    .addComponent(btObra)
                    .addComponent(btPersonagem)
                    .addComponent(btLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btLocal, btObra, btPersonagem, btTermo});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btLocal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btPersonagem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btObra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btTermo)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLocalActionPerformed
     
    }//GEN-LAST:event_btLocalActionPerformed

    private void btPersonagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPersonagemMouseClicked
        Cad_Personagem personagem = new Cad_Personagem(); 
        personagem.setVisible(true);
    }//GEN-LAST:event_btPersonagemMouseClicked

    private void btlocalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btlocalMouseClicked
      Cad_Local local = new Cad_Local(); 
       local.setVisible(true);
    }//GEN-LAST:event_btlocalMouseClicked

    private void btObraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btObraMouseClicked
       Cad_Obra obra = new Cad_Obra(); 
       obra.setVisible(true);
    }//GEN-LAST:event_btObraMouseClicked

    private void btTermoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTermoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btTermoActionPerformed

    private void btTermoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btTermoMouseClicked
        Cad_Termo termo = new Cad_Termo(); 
        termo.setVisible(true);
    }//GEN-LAST:event_btTermoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
  
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Inicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLocal;
    private javax.swing.JButton btObra;
    private javax.swing.JButton btPersonagem;
    private javax.swing.JButton btTermo;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
